### PR TITLE
uprev curve25519-dalek

### PR DESCRIPTION
**Pull request by eranrund**

### CODE REVIEW

**Review by nick-mobilecoin — APPROVED** [review]
LGTM
looks like we have some warnings, but it's better than the failures on the mainline right now :(
```console
➜  schnorrkel git:(uprev-curve25519-dalek) cargo build            
   Compiling curve25519-dalek v4.1.0
   Compiling schnorrkel-og v0.11.0-pre.0 (/home/nick/git/schnorrkel)
warning: use of deprecated associated function `curve25519_dalek::Scalar::from_bits`: This constructor outputs scalars with undefined scalar-scalar arithmetic. See docs.
   --> src/keys.rs:198:27
    |
198 |         let key = Scalar::from_bits(key);
    |                           ^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `curve25519_dalek::Scalar::from_bits`: This constructor outputs scalars with undefined scalar-scalar arithmetic. See docs.
   --> src/keys.rs:527:27
    |
527 |         let key = Scalar::from_bits(key);
    |                           ^^^^^^^^^

warning: use of deprecated associated function `curve25519_dalek::Scalar::from_bits`: This constructor outputs scalars with undefined scalar-scalar arithmetic. See docs.
  --> src/sign.rs:75:27
   |
75 |         return Ok(Scalar::from_bits(bytes))
   |                           ^^^^^^^^^

warning: `schnorrkel-og` (lib) generated 3 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.90s
```

**Comment by eranrund** [comment]
Yes, that `from_bits` API was deprecated. I wonder if we need this fork at all at this point, maybe we can switch back to https://github.com/w3f/schnorrkel/?
I'll look into it down the line, but right now I think the warnings are fine.

**Comment by eranrund** [comment]
https://github.com/w3f/schnorrkel/blob/master/src/keys.rs#L200C27-L201 is how one such warning is addressed in the original repo...

**Comment by nick-mobilecoin** [comment]
> https://github.com/w3f/schnorrkel/blob/master/src/keys.rs#L200C27-L201 is how one such warning is addressed in the original repo...

I think the warnings are fine for now. My understanding is they only show up when building this crate directly, and will only be seen by consumers if they do the `-vv` flag when building.

**Pull request merged**
